passthruUnmapped: false

media:
  image:
    library:
      - src: https://images.microcms-assets.io/assets/
        kind: imgix

# items と total フィールドがルート直下になるように変形する.
transform: data.collection.{"items":[collection.link]}

flds:
  - query: $replace(_meta.uid, /^[^-]+-/, "")
    dstName: id
    fldType: id

  - query: title.text
    dstName: title
    fldType: string

  # RichText を HTML として扱う.
  # Prismic では配列をわされるので remote-cms-content 内でライブラリを用いて変換する.
  - query: content
    dstName: content
    fldType: html
    convert: none
    toMarkdownOpts:
      # Prismic では画像の属性は付かないが指定だけはしておく.
      imageSalt:
        - command: rebuild
          baseURL: https://images.prismic.io/
          embed:
            embedTo: alt

  - query: description.text
    dstName: description
    fldType: string

  - query: category.title.text
    dstName: category
    fldType: string

  - query: fullscreen
    dstName: fullscreen
    fldType: boolean

  - query: version
    dstName: version
    fldType: string

  # pricmis では API ID に大文字は使えないもよう.
  - query: menutitle.text
    dstName: menuTitle
    fldType: string

  - query: subtitle.text
    dstName: subtitle
    fldType: string

  - query: badge
    dstName: badge
    fldType: string

  - query: list.item
    dstName: list
    fldType: object
